import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import React from "react";
import Link from "next/link";
import NavigationMenu from "@/components/NavigationMenu";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const navigationItems = [
    {path: "/", label: "Home"},
    {path: "/movies", label: "Movies"},
    {path: "/shows", label: "Shows"},
    {path: "/mylist", label: "My List"},
];

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        {/* TOP BAR NAVIGATION */}
        <header className="text-white p-4">
            <div className="container mx-auto flex justify-between items-center">

                {/* APPLICATION LOGO */}
                <div className="items-center">
                    <Link href="/" className="text-2xl font-bold">
                        MY-FLIX
                    </Link>
                </div>

                <NavigationMenu items={navigationItems}/>

                {/* SEARCH */}
                <div className="items-center">
                    <Link href="/search">
                        Search
                    </Link>
                </div>
            </div>
        </header>

        {children}

        </body>
        </html>
    );
}
